name: Run Hello-world from py script
on: push

jobs:
    Hello:
        runs-on: ubuntu-latest

        steps:
        - name: Clone repo
          uses: actions/checkout@v4  

        - name: setup python 
          uses: actions/setup-python@v6
          with:
            python-version: '3.13' 
        - run: python my_script.py  
         
        - name: Run a py script
          run: python hello.py  
        